### ISSUE TITLE
readme.md needs updating to remove use of mbiedata

### ISSUE THREAD

**Issue by cauldnz** [nz-mbie/mbie-r-package-public#1]
I use `devtools` to install the package. The package name is `mbie` and not `mbiedata` and as such [readme.md](url) is incorrect.

**Comment by ellisp** [comment]
`mbiedata` is a separate package that we are planning on decommissioning (it predates the current data warehousing environment in MBIE).  I'll change this issue to reflect the need to update the readme.

**Comment by HaizhenWu** [comment]
Took the easiest approach: pack the data used by readme.rmd into https://github.com/nz-mbie/mbie-r-package-public/blob/master/raw_data/mbie-r-package-public-example-data.rda?raw=true and remove mbiedata package from it. 

readme.rmd will download the data file from https://github.com/nz-mbie/mbie-r-package-public/blob/master/raw_data/mbie-r-package-public-example-data.rda?raw=true with "wb" mode if no local version available. 

readme.rmd has been gone through to fix some bugs and reaeme.html has been rebuilt.

**Comment by HaizhenWu** [comment]
readme.md update and the issue should have been fixed. 

@cauldnz , please note that we just upgrade the public version of mbie package here from 0.9.5 to 0.9.7. And you may want to test the new version as well.
