### ISSUE TITLE
Package masks `install.packages`

### ISSUE THREAD

**Issue by cauldnz** [nz-mbie/mbie-r-package-public#2]
This package masks `install.packages`. Guessing this is to manage internal MBIE package workflow but will be a problem for most external users I think.

```r
> install.packages("ggthemes")
Error in install.packages("ggthemes") : 
  To request new packages please contact Sam Vennell (Sam.Vennell@mbie.govt.nz), Eric Wu (Eric.Wu@mbie.govt.nz) or Peter Ellis (Peter.Ellis@mbie.govt.nz).

```

**Comment by ellisp** [comment]
yes, sorry about this... it is very much an internal package and published on a caveat emptor basis, as much for transparency as anything else...  @HaizhenWu is it possible to adapt our masking `install.packages()` function so it checks to see if it is the MBIE environment, and if not just passing through to the base installation install.packages()

**Comment by HaizhenWu** [comment]
The pkg/R/dummyfunctions.R has been updated, such that `install.packages()` will use `util::install.packages()` if not in MBIE environment. 

@cauldnz, please re-install the package and test the install.packages() outside MBIE.

**Comment by cauldnz** [comment]
Thanks folks. Can confirm that new build now passes through. As a bit of context, we were using this package during the Statistics NZ Datarama Hackfest event on Saturday. Was great to be able to use this and I am certainly pushing Stats for an R package for their stuff moving forward. Love to buy you guys coffee next time I am in WLG!
